### PR TITLE
fix rights when changing uid that avoid service to start

### PR DESCRIPTION
**Pull request by deimosfr**
Hi,

This fix makes service start. There was an issue when changing uid and not log file. If no file permission was given to log folder, then service refuse to start.

Can you please merge and make a new tag for it.

Thanks

### CODE REVIEW

**Comment by klen** [comment]
Thank you!

**Comment by deimosfr** [comment]
Can you please release a new version ?

Thanks

**Comment by klen** [comment]
Already did

**Comment by deimosfr** [comment]
Nice thanks

**Pull request merged**
